name: "Setup and install (pnpm)"
description: "setting up pnpm as runtime"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v6

    - name: setup pnpm
      uses: pnpm/setup@v1
      with:
        version: 11
        runtime: node@24
        cache: true

    - name: setup node
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: pnpm

    - shell: bash
      run: pnpm install
