name: "CI"

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup (pnpm + node + install)
        uses: ./tooling/setup

      - name: Lint (oxlint)
        run: pnpm lint -f github

      - name: Format (oxfmt)
        run: pnpm format:check

      - name: Types (tsc)
        run: pnpm typecheck

      - name: Install Vercel CLI
        run: pnpm i -g vercel@latest

      - name: Pull Vercel env info
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build project artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
