name: PRs

on: [push, pull_request]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

jobs: 
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Create .env.local file
      run: |
        echo "DATABASE_URL=${{ env.DATABASE_URL }}" > .env.local
        echo "SUPABASE_URL=${{ env.SUPABASE_URL }}" >> .env.local
        echo "SUPABASE_ANON_KEY=${{ env.SUPABASE_ANON_KEY }}" >> .env.local

    - name: Upload .env.local as artifact
      uses: actions/upload-artifact@v2
      with:
        name: .env.local
        path: .env.local

  test:
    runs-on: ubuntu-latest
    needs: setup  

    steps: 
    - name: Checkout code 
      uses: actions/checkout@v3

    - name: Download .env.local artifact  
      uses: actions/download-artifact@v2
      with:
        name: .env.local

    - name: Securely use environment variables  
      run: |
        source .env.local && echo "Secrets are loaded"

    # - name: Run Tests  
    #   run: npm test
